// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://simhudiwzoqfygbecsch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpbWh1ZGl3em9xZnlnYmVjc2NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTYwMDgsImV4cCI6MjA2OTU3MjAwOH0.AztmCj2_Lur-Sf914-y5MNW1Rlh7zTXg8Qed2rPuRss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});